import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { Toaster } from "react-hot-toast";
import HomePageHeartbeat from "@/hooks/HeartBeat";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DC Games Manager | ItsMe Prince",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<div>loading ...</div>}>
          <HomePageHeartbeat />
          {children}
          <Toaster
            position="bottom-left"
            toastOptions={{
              style: {
                fontSize: "14px",
                background: "black",
                color: "white",
              },
            }}
          />
        </Suspense>
      </body>
    </html>
  );
}
