import "./globals.css";

import type { Metadata } from "next";
import { Suspense } from "react";
import { Toaster } from "react-hot-toast";
import { SessionProviderNextAuth } from "./(components)/SessionProvider";

import HomePageHeartbeat from "../hooks/HeartBeat";

export const metadata: Metadata = {
  title: "DC Games Manager | ItsMe Prince",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProviderNextAuth>
          <Suspense fallback={<div>loading ...</div>}>
            <HomePageHeartbeat />
            {children}
            <Toaster
              position="bottom-left"
              toastOptions={{
                style: {
                  fontSize: "14px",
                  background: "black",
                  color: "white",
                },
              }}
            />
          </Suspense>
        </SessionProviderNextAuth>
      </body>
    </html>
  );
}
